//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mh.Service.WebApi.BarkodokuComService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BarkodSonuc", Namespace="http://barkodoku.com/")]
    [System.SerializableAttribute()]
    public partial class BarkodSonuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mh.Service.WebApi.BarkodokuComService.Barkod UrunBarkodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mh.Service.WebApi.BarkodokuComService.Hata HataMesajiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mh.Service.WebApi.BarkodokuComService.BarkodCozum BarkodCozumuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mh.Service.WebApi.BarkodokuComService.KotaBilgi KotaBilgisiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Mh.Service.WebApi.BarkodokuComService.Barkod UrunBarkod {
            get {
                return this.UrunBarkodField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunBarkodField, value) != true)) {
                    this.UrunBarkodField = value;
                    this.RaisePropertyChanged("UrunBarkod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Mh.Service.WebApi.BarkodokuComService.Hata HataMesaji {
            get {
                return this.HataMesajiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataMesajiField, value) != true)) {
                    this.HataMesajiField = value;
                    this.RaisePropertyChanged("HataMesaji");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Mh.Service.WebApi.BarkodokuComService.BarkodCozum BarkodCozumu {
            get {
                return this.BarkodCozumuField;
            }
            set {
                if ((object.ReferenceEquals(this.BarkodCozumuField, value) != true)) {
                    this.BarkodCozumuField = value;
                    this.RaisePropertyChanged("BarkodCozumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Mh.Service.WebApi.BarkodokuComService.KotaBilgi KotaBilgisi {
            get {
                return this.KotaBilgisiField;
            }
            set {
                if ((object.ReferenceEquals(this.KotaBilgisiField, value) != true)) {
                    this.KotaBilgisiField = value;
                    this.RaisePropertyChanged("KotaBilgisi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Barkod", Namespace="http://barkodoku.com/")]
    [System.SerializableAttribute()]
    public partial class Barkod : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunBarkodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrunDetayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarkodTipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mh.Service.WebApi.BarkodokuComService.Firma UreticiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mh.Service.WebApi.BarkodokuComService.Fiyat[] UrunFiyatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrunBarkod {
            get {
                return this.UrunBarkodField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunBarkodField, value) != true)) {
                    this.UrunBarkodField = value;
                    this.RaisePropertyChanged("UrunBarkod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UrunAd {
            get {
                return this.UrunAdField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunAdField, value) != true)) {
                    this.UrunAdField = value;
                    this.RaisePropertyChanged("UrunAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UrunDetay {
            get {
                return this.UrunDetayField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunDetayField, value) != true)) {
                    this.UrunDetayField = value;
                    this.RaisePropertyChanged("UrunDetay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BarkodTip {
            get {
                return this.BarkodTipField;
            }
            set {
                if ((object.ReferenceEquals(this.BarkodTipField, value) != true)) {
                    this.BarkodTipField = value;
                    this.RaisePropertyChanged("BarkodTip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Mh.Service.WebApi.BarkodokuComService.Firma Uretici {
            get {
                return this.UreticiField;
            }
            set {
                if ((object.ReferenceEquals(this.UreticiField, value) != true)) {
                    this.UreticiField = value;
                    this.RaisePropertyChanged("Uretici");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Mh.Service.WebApi.BarkodokuComService.Fiyat[] UrunFiyat {
            get {
                return this.UrunFiyatField;
            }
            set {
                if ((object.ReferenceEquals(this.UrunFiyatField, value) != true)) {
                    this.UrunFiyatField = value;
                    this.RaisePropertyChanged("UrunFiyat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hata", Namespace="http://barkodoku.com/")]
    [System.SerializableAttribute()]
    public partial class Hata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataAciklamaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HataKodu {
            get {
                return this.HataKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.HataKoduField, value) != true)) {
                    this.HataKoduField = value;
                    this.RaisePropertyChanged("HataKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HataAciklama {
            get {
                return this.HataAciklamaField;
            }
            set {
                if ((object.ReferenceEquals(this.HataAciklamaField, value) != true)) {
                    this.HataAciklamaField = value;
                    this.RaisePropertyChanged("HataAciklama");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BarkodCozum", Namespace="http://barkodoku.com/")]
    [System.SerializableAttribute()]
    public partial class BarkodCozum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenseiField;
        
        private int UreticiKoduField;
        
        private int UrunKoduField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensei {
            get {
                return this.MenseiField;
            }
            set {
                if ((object.ReferenceEquals(this.MenseiField, value) != true)) {
                    this.MenseiField = value;
                    this.RaisePropertyChanged("Mensei");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UreticiKodu {
            get {
                return this.UreticiKoduField;
            }
            set {
                if ((this.UreticiKoduField.Equals(value) != true)) {
                    this.UreticiKoduField = value;
                    this.RaisePropertyChanged("UreticiKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UrunKodu {
            get {
                return this.UrunKoduField;
            }
            set {
                if ((this.UrunKoduField.Equals(value) != true)) {
                    this.UrunKoduField = value;
                    this.RaisePropertyChanged("UrunKodu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KotaBilgi", Namespace="http://barkodoku.com/")]
    [System.SerializableAttribute()]
    public partial class KotaBilgi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int KalanKotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int KalanKota {
            get {
                return this.KalanKotaField;
            }
            set {
                if ((this.KalanKotaField.Equals(value) != true)) {
                    this.KalanKotaField = value;
                    this.RaisePropertyChanged("KalanKota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Firma", Namespace="http://barkodoku.com/")]
    [System.SerializableAttribute()]
    public partial class Firma : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaAdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaSehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaIlceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaTelefonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaFaksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Firma444Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaSektorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaWebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaLogoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirmaAdi {
            get {
                return this.FirmaAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaAdiField, value) != true)) {
                    this.FirmaAdiField = value;
                    this.RaisePropertyChanged("FirmaAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirmaAdres {
            get {
                return this.FirmaAdresField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaAdresField, value) != true)) {
                    this.FirmaAdresField = value;
                    this.RaisePropertyChanged("FirmaAdres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FirmaSehir {
            get {
                return this.FirmaSehirField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaSehirField, value) != true)) {
                    this.FirmaSehirField = value;
                    this.RaisePropertyChanged("FirmaSehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirmaIlce {
            get {
                return this.FirmaIlceField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaIlceField, value) != true)) {
                    this.FirmaIlceField = value;
                    this.RaisePropertyChanged("FirmaIlce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string FirmaTelefon {
            get {
                return this.FirmaTelefonField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaTelefonField, value) != true)) {
                    this.FirmaTelefonField = value;
                    this.RaisePropertyChanged("FirmaTelefon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FirmaFaks {
            get {
                return this.FirmaFaksField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaFaksField, value) != true)) {
                    this.FirmaFaksField = value;
                    this.RaisePropertyChanged("FirmaFaks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Firma444 {
            get {
                return this.Firma444Field;
            }
            set {
                if ((object.ReferenceEquals(this.Firma444Field, value) != true)) {
                    this.Firma444Field = value;
                    this.RaisePropertyChanged("Firma444");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string FirmaSektor {
            get {
                return this.FirmaSektorField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaSektorField, value) != true)) {
                    this.FirmaSektorField = value;
                    this.RaisePropertyChanged("FirmaSektor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string FirmaWeb {
            get {
                return this.FirmaWebField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaWebField, value) != true)) {
                    this.FirmaWebField = value;
                    this.RaisePropertyChanged("FirmaWeb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string FirmaLogo {
            get {
                return this.FirmaLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaLogoField, value) != true)) {
                    this.FirmaLogoField = value;
                    this.RaisePropertyChanged("FirmaLogo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fiyat", Namespace="http://barkodoku.com/")]
    [System.SerializableAttribute()]
    public partial class Fiyat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double UrunFiyatField;
        
        private System.DateTime FiyatTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mh.Service.WebApi.BarkodokuComService.Mekan FiyatMekanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double UrunFiyat {
            get {
                return this.UrunFiyatField;
            }
            set {
                if ((this.UrunFiyatField.Equals(value) != true)) {
                    this.UrunFiyatField = value;
                    this.RaisePropertyChanged("UrunFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime FiyatTarih {
            get {
                return this.FiyatTarihField;
            }
            set {
                if ((this.FiyatTarihField.Equals(value) != true)) {
                    this.FiyatTarihField = value;
                    this.RaisePropertyChanged("FiyatTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Mh.Service.WebApi.BarkodokuComService.Mekan FiyatMekan {
            get {
                return this.FiyatMekanField;
            }
            set {
                if ((object.ReferenceEquals(this.FiyatMekanField, value) != true)) {
                    this.FiyatMekanField = value;
                    this.RaisePropertyChanged("FiyatMekan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mekan", Namespace="http://barkodoku.com/")]
    [System.SerializableAttribute()]
    public partial class Mekan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MekanAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MekanAdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MekanSehirField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MekanAdi {
            get {
                return this.MekanAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.MekanAdiField, value) != true)) {
                    this.MekanAdiField = value;
                    this.RaisePropertyChanged("MekanAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MekanAdres {
            get {
                return this.MekanAdresField;
            }
            set {
                if ((object.ReferenceEquals(this.MekanAdresField, value) != true)) {
                    this.MekanAdresField = value;
                    this.RaisePropertyChanged("MekanAdres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MekanSehir {
            get {
                return this.MekanSehirField;
            }
            set {
                if ((object.ReferenceEquals(this.MekanSehirField, value) != true)) {
                    this.MekanSehirField = value;
                    this.RaisePropertyChanged("MekanSehir");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://barkodoku.com/", ConfigurationName="BarkodokuComService.BarkodServisSoap")]
    public interface BarkodServisSoap {
        
        // CODEGEN: Generating message contract since element name MerhabaResult from namespace http://barkodoku.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/Merhaba", ReplyAction="*")]
        Mh.Service.WebApi.BarkodokuComService.MerhabaResponse Merhaba(Mh.Service.WebApi.BarkodokuComService.MerhabaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/Merhaba", ReplyAction="*")]
        System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.MerhabaResponse> MerhabaAsync(Mh.Service.WebApi.BarkodokuComService.MerhabaRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://barkodoku.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/BarkodGetir", ReplyAction="*")]
        Mh.Service.WebApi.BarkodokuComService.BarkodGetirResponse BarkodGetir(Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/BarkodGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.BarkodGetirResponse> BarkodGetirAsync(Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://barkodoku.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/KotaSorgula", ReplyAction="*")]
        Mh.Service.WebApi.BarkodokuComService.KotaSorgulaResponse KotaSorgula(Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/KotaSorgula", ReplyAction="*")]
        System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.KotaSorgulaResponse> KotaSorgulaAsync(Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://barkodoku.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/QRKodOlustur", ReplyAction="*")]
        Mh.Service.WebApi.BarkodokuComService.QRKodOlusturResponse QRKodOlustur(Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://barkodoku.com/QRKodOlustur", ReplyAction="*")]
        System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.QRKodOlusturResponse> QRKodOlusturAsync(Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MerhabaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Merhaba", Namespace="http://barkodoku.com/", Order=0)]
        public Mh.Service.WebApi.BarkodokuComService.MerhabaRequestBody Body;
        
        public MerhabaRequest() {
        }
        
        public MerhabaRequest(Mh.Service.WebApi.BarkodokuComService.MerhabaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MerhabaRequestBody {
        
        public MerhabaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MerhabaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MerhabaResponse", Namespace="http://barkodoku.com/", Order=0)]
        public Mh.Service.WebApi.BarkodokuComService.MerhabaResponseBody Body;
        
        public MerhabaResponse() {
        }
        
        public MerhabaResponse(Mh.Service.WebApi.BarkodokuComService.MerhabaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class MerhabaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerhabaResult;
        
        public MerhabaResponseBody() {
        }
        
        public MerhabaResponseBody(string MerhabaResult) {
            this.MerhabaResult = MerhabaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BarkodGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BarkodGetir", Namespace="http://barkodoku.com/", Order=0)]
        public Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequestBody Body;
        
        public BarkodGetirRequest() {
        }
        
        public BarkodGetirRequest(Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class BarkodGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string barkod;
        
        public BarkodGetirRequestBody() {
        }
        
        public BarkodGetirRequestBody(string apiKey, string barkod) {
            this.apiKey = apiKey;
            this.barkod = barkod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BarkodGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BarkodGetirResponse", Namespace="http://barkodoku.com/", Order=0)]
        public Mh.Service.WebApi.BarkodokuComService.BarkodGetirResponseBody Body;
        
        public BarkodGetirResponse() {
        }
        
        public BarkodGetirResponse(Mh.Service.WebApi.BarkodokuComService.BarkodGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class BarkodGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mh.Service.WebApi.BarkodokuComService.BarkodSonuc BarkodGetirResult;
        
        public BarkodGetirResponseBody() {
        }
        
        public BarkodGetirResponseBody(Mh.Service.WebApi.BarkodokuComService.BarkodSonuc BarkodGetirResult) {
            this.BarkodGetirResult = BarkodGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KotaSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KotaSorgula", Namespace="http://barkodoku.com/", Order=0)]
        public Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequestBody Body;
        
        public KotaSorgulaRequest() {
        }
        
        public KotaSorgulaRequest(Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class KotaSorgulaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public KotaSorgulaRequestBody() {
        }
        
        public KotaSorgulaRequestBody(string apiKey) {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KotaSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KotaSorgulaResponse", Namespace="http://barkodoku.com/", Order=0)]
        public Mh.Service.WebApi.BarkodokuComService.KotaSorgulaResponseBody Body;
        
        public KotaSorgulaResponse() {
        }
        
        public KotaSorgulaResponse(Mh.Service.WebApi.BarkodokuComService.KotaSorgulaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class KotaSorgulaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int KotaSorgulaResult;
        
        public KotaSorgulaResponseBody() {
        }
        
        public KotaSorgulaResponseBody(int KotaSorgulaResult) {
            this.KotaSorgulaResult = KotaSorgulaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QRKodOlusturRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QRKodOlustur", Namespace="http://barkodoku.com/", Order=0)]
        public Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequestBody Body;
        
        public QRKodOlusturRequest() {
        }
        
        public QRKodOlusturRequest(Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class QRKodOlusturRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string veri;
        
        public QRKodOlusturRequestBody() {
        }
        
        public QRKodOlusturRequestBody(string apiKey, string veri) {
            this.apiKey = apiKey;
            this.veri = veri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QRKodOlusturResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QRKodOlusturResponse", Namespace="http://barkodoku.com/", Order=0)]
        public Mh.Service.WebApi.BarkodokuComService.QRKodOlusturResponseBody Body;
        
        public QRKodOlusturResponse() {
        }
        
        public QRKodOlusturResponse(Mh.Service.WebApi.BarkodokuComService.QRKodOlusturResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://barkodoku.com/")]
    public partial class QRKodOlusturResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string QRKodOlusturResult;
        
        public QRKodOlusturResponseBody() {
        }
        
        public QRKodOlusturResponseBody(string QRKodOlusturResult) {
            this.QRKodOlusturResult = QRKodOlusturResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BarkodServisSoapChannel : Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BarkodServisSoapClient : System.ServiceModel.ClientBase<Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap>, Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap {
        
        public BarkodServisSoapClient() {
        }
        
        public BarkodServisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BarkodServisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarkodServisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarkodServisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mh.Service.WebApi.BarkodokuComService.MerhabaResponse Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap.Merhaba(Mh.Service.WebApi.BarkodokuComService.MerhabaRequest request) {
            return base.Channel.Merhaba(request);
        }
        
        public string Merhaba() {
            Mh.Service.WebApi.BarkodokuComService.MerhabaRequest inValue = new Mh.Service.WebApi.BarkodokuComService.MerhabaRequest();
            inValue.Body = new Mh.Service.WebApi.BarkodokuComService.MerhabaRequestBody();
            Mh.Service.WebApi.BarkodokuComService.MerhabaResponse retVal = ((Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap)(this)).Merhaba(inValue);
            return retVal.Body.MerhabaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.MerhabaResponse> Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap.MerhabaAsync(Mh.Service.WebApi.BarkodokuComService.MerhabaRequest request) {
            return base.Channel.MerhabaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.MerhabaResponse> MerhabaAsync() {
            Mh.Service.WebApi.BarkodokuComService.MerhabaRequest inValue = new Mh.Service.WebApi.BarkodokuComService.MerhabaRequest();
            inValue.Body = new Mh.Service.WebApi.BarkodokuComService.MerhabaRequestBody();
            return ((Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap)(this)).MerhabaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mh.Service.WebApi.BarkodokuComService.BarkodGetirResponse Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap.BarkodGetir(Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequest request) {
            return base.Channel.BarkodGetir(request);
        }
        
        public Mh.Service.WebApi.BarkodokuComService.BarkodSonuc BarkodGetir(string apiKey, string barkod) {
            Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequest inValue = new Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequest();
            inValue.Body = new Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.barkod = barkod;
            Mh.Service.WebApi.BarkodokuComService.BarkodGetirResponse retVal = ((Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap)(this)).BarkodGetir(inValue);
            return retVal.Body.BarkodGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.BarkodGetirResponse> Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap.BarkodGetirAsync(Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequest request) {
            return base.Channel.BarkodGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.BarkodGetirResponse> BarkodGetirAsync(string apiKey, string barkod) {
            Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequest inValue = new Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequest();
            inValue.Body = new Mh.Service.WebApi.BarkodokuComService.BarkodGetirRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.barkod = barkod;
            return ((Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap)(this)).BarkodGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mh.Service.WebApi.BarkodokuComService.KotaSorgulaResponse Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap.KotaSorgula(Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequest request) {
            return base.Channel.KotaSorgula(request);
        }
        
        public int KotaSorgula(string apiKey) {
            Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequest inValue = new Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequest();
            inValue.Body = new Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequestBody();
            inValue.Body.apiKey = apiKey;
            Mh.Service.WebApi.BarkodokuComService.KotaSorgulaResponse retVal = ((Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap)(this)).KotaSorgula(inValue);
            return retVal.Body.KotaSorgulaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.KotaSorgulaResponse> Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap.KotaSorgulaAsync(Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequest request) {
            return base.Channel.KotaSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.KotaSorgulaResponse> KotaSorgulaAsync(string apiKey) {
            Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequest inValue = new Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequest();
            inValue.Body = new Mh.Service.WebApi.BarkodokuComService.KotaSorgulaRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap)(this)).KotaSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mh.Service.WebApi.BarkodokuComService.QRKodOlusturResponse Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap.QRKodOlustur(Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequest request) {
            return base.Channel.QRKodOlustur(request);
        }
        
        public string QRKodOlustur(string apiKey, string veri) {
            Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequest inValue = new Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequest();
            inValue.Body = new Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.veri = veri;
            Mh.Service.WebApi.BarkodokuComService.QRKodOlusturResponse retVal = ((Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap)(this)).QRKodOlustur(inValue);
            return retVal.Body.QRKodOlusturResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.QRKodOlusturResponse> Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap.QRKodOlusturAsync(Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequest request) {
            return base.Channel.QRKodOlusturAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mh.Service.WebApi.BarkodokuComService.QRKodOlusturResponse> QRKodOlusturAsync(string apiKey, string veri) {
            Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequest inValue = new Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequest();
            inValue.Body = new Mh.Service.WebApi.BarkodokuComService.QRKodOlusturRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.veri = veri;
            return ((Mh.Service.WebApi.BarkodokuComService.BarkodServisSoap)(this)).QRKodOlusturAsync(inValue);
        }
    }
}
